name = "Shaders"
uuid = "1414e3f1-87ca-4282-8e22-8f0dcb1dc9b4"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
CSyntax = "ea656a56-6ca6-5dda-bba5-7b6963a5f74c"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301" 
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]

[compat]
julia = "1"
Revise = "2.5"
MacroTools = "0.5"
